# Form implementation generated from reading ui file 'h:\Проекты\Для лабы\PersonAdaptationExperiments\forms\select_video_input_window\ui_SelectVideoInputWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectVideoInputWindow(object):
    def setupUi(self, SelectVideoInputWindow):
        SelectVideoInputWindow.setObjectName("SelectVideoInputWindow")
        SelectVideoInputWindow.resize(800, 569)
        SelectVideoInputWindow.setMinimumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(parent=SelectVideoInputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.video_widget = QVideoWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_widget.sizePolicy().hasHeightForWidth())
        self.video_widget.setSizePolicy(sizePolicy)
        self.video_widget.setObjectName("video_widget")
        self.verticalLayout_2.addWidget(self.video_widget)
        SelectVideoInputWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SelectVideoInputWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menu_devices = QtWidgets.QMenu(parent=self.menubar)
        self.menu_devices.setObjectName("menu_devices")
        self.menu_actions = QtWidgets.QMenu(parent=self.menubar)
        self.menu_actions.setObjectName("menu_actions")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        SelectVideoInputWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SelectVideoInputWindow)
        self.statusbar.setObjectName("statusbar")
        SelectVideoInputWindow.setStatusBar(self.statusbar)
        self.action_confirm_select = QtGui.QAction(parent=SelectVideoInputWindow)
        self.action_confirm_select.setObjectName("action_confirm_select")
        self.action_rotate_clockwise = QtGui.QAction(parent=SelectVideoInputWindow)
        self.action_rotate_clockwise.setObjectName("action_rotate_clockwise")
        self.action_rotate_counter_clockwise = QtGui.QAction(parent=SelectVideoInputWindow)
        self.action_rotate_counter_clockwise.setObjectName("action_rotate_counter_clockwise")
        self.action_mirror = QtGui.QAction(parent=SelectVideoInputWindow)
        self.action_mirror.setCheckable(True)
        self.action_mirror.setObjectName("action_mirror")
        self.menu_actions.addAction(self.action_confirm_select)
        self.menu.addAction(self.action_rotate_clockwise)
        self.menu.addAction(self.action_rotate_counter_clockwise)
        self.menu.addAction(self.action_mirror)
        self.menubar.addAction(self.menu_devices.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_actions.menuAction())

        self.retranslateUi(SelectVideoInputWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectVideoInputWindow)

    def retranslateUi(self, SelectVideoInputWindow):
        _translate = QtCore.QCoreApplication.translate
        SelectVideoInputWindow.setWindowTitle(_translate("SelectVideoInputWindow", "Выбор видеовхода"))
        self.menu_devices.setTitle(_translate("SelectVideoInputWindow", "Устройства"))
        self.menu_actions.setTitle(_translate("SelectVideoInputWindow", "Действия"))
        self.menu.setTitle(_translate("SelectVideoInputWindow", "Изменение изображения"))
        self.action_confirm_select.setText(_translate("SelectVideoInputWindow", "Подтвердить выбор"))
        self.action_rotate_clockwise.setText(_translate("SelectVideoInputWindow", "Поворот по часовой"))
        self.action_rotate_counter_clockwise.setText(_translate("SelectVideoInputWindow", "Поворот против часовой"))
        self.action_mirror.setText(_translate("SelectVideoInputWindow", "Отразить зеркально"))
from PyQt6.QtMultimediaWidgets import QVideoWidget
